{{- if .Values.config_map }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  "{{ include "pet-battle.fullname" . }}-nginx"
  labels:
    {{- include "pet-battle.labels" . | nindent 4 }}
data:
  server.conf: |-

    upstream test {
      server test-api:8080;
    }

    server {
      listen       8080 default_server;
      listen       [::]:8080 default_server;
      server_name  _;
      root         /opt/app-root/src;

      # Load configuration files for the default server block.
      include             /etc/nginx/mime.types;
      default_type        application/octet-stream;
      # resolver            172.30.0.10:53;

      set $pb pet-battle-api:8080;
      location ~ ^/cats/(.*)$ {
      # location /cats/ {
        proxy_set_header  X-Request-Id $request_id;
        # proxy_pass        http://$pb/cats/$1$is_args$args;
        proxy_pass        http://pet-battle-api.ateam.svc.cluster.local:8080/cats/$1$is_args$args;
        proxy_set_header  Host $host;
      }

      location / {
          try_files $uri $uri/ /index.html;
      }

      # set $kc keycloak;
      # location /auth {
      #     proxy_set_header X-Request-Id $request_id;
      #     proxy_pass http://$kc;
      #     proxy_set_header Host $host;
      # }

      upstream pb {
        # works but ONLY IF pet-battle-api is available
        server pet-battle-api:8080; 
      }
      location /cats/ {
        proxy_pass http://$pb
      }
      
      
      resolver 172.30.0.10:53;
      set $pb3 http://pet-battle-api.ateam-test.svc.cluster.local:8080;
      location /cats/ {
        proxy_pass http://$pb3;
      }

      error_page 404 /404.html;
      location = /40x.html {
      }

      error_page 500 502 503 504  /50x.html;
      location = /50x.html {
      }
    }
{{- end }}